### ISSUE TITLE
Rebuild for LEDE

### ISSUE THREAD

**Issue by riptidewave93** [riptidewave93/LEDE-APU2#1]
As most of the "Development" behind OpenWRT left for LEDE, this branch will get rebuilt for "mainstream" LEDE support, including the LED/Button driver.

**Comment by Gr4ffy** [comment]
Hi,

Try this one, I made some improvements:
- AES-NI support
- NCT5104 GPIO driver
- watchdog driver ( I2C or watchdog, they can't work together )
- SD/MMC driver
- PC Speaker
- CPU scaling ( default - ondemand )

,but i don't know how detect apu board and set leds/ethernet ports :(
I'm counting on you :)
[LEDE-APU2.tar.gz](https://github.com/riptidewave93/Openwrt-APU2/files/485191/LEDE-APU2.tar.gz)

**Comment by riptidewave93** [comment]
Hey Gr4ffy, thanks for the submission. I can gladly help get the LED driver and board detection working. If you don't mind, do you care if I create 2 new branches (one for i2c, one for watchdog) using your shared files? If you want credit for the changes, I can make the branches which you can then submit PR requests against. Once done, I can then get the LED driver integration going.

**Comment by Gr4ffy** [comment]
No problem, do what you have to do.
I don't need any credits, just use it.

PS. Sorry for my English ;)

**Comment by riptidewave93** [comment]
Gr4ffy, no worries and will have the branches done within the next few hours so you can test/verify them. And yes, I will add the LED/Button support. :)

**Comment by riptidewave93** [comment]
@Gr4ffy Initial test is at https://github.com/riptidewave93/Openwrt-APU2/tree/lede-watchdog, if you could build it and confirm it works as intended, that would be great. I can then work on the i2c branch. I no longer run OpenWRT/LEDE so I am unable to test on my APU2C4.

If not, can you please share with me the contents of the files in /tmp/sysinfo ?

**Comment by Gr4ffy** [comment]
Ok

**Comment by Gr4ffy** [comment]
Hi @riptidewave93

I made some tests but the image wasn't build fine.
I made another image - basic+nano+gpio/leds+aes_ni+speaker+watchdog
 [LEDE-APU2.tar.gz](https://github.com/riptidewave93/Openwrt-APU2/files/487778/LEDE-APU2.tar.gz)
I used your board detection but with no luck.
Only ethernets ports are set fine eth0 -> WAN / eth1 -> LAN, take a look:

```
root@lede:~# cat /tmp/sysinfo/board_name
pc-engines-apu2
root@lede:~# cat /tmp/sysinfo/model
PC Engines apu2

root@lede:# ls /sys/class/leds/
apu2:green:led2   apu2:green:led3   apu2:green:power  ath9k-phy0        mmc0::

root@lede:/# ls /sys/class/gpio
export       gpiochip0    gpiochip10   gpiochip498  gpiochip508  unexport

root@lede:/# cat /etc/config/network
config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fd10:a91e:dc8a::/48'

config interface 'lan'
        option type 'bridge'
        option ifname 'eth1'
        option proto 'static'
        option ipaddr '192.168.1.1'
        option netmask '255.255.255.0'
        option ip6assign '60'

config interface 'wan'
        option ifname 'eth0'
        option proto 'dhcp'

config interface 'wan6'
        option ifname 'eth0'
        option proto 'dhcpv6'

root@lede:/# cat /etc/config/system
config system
        option hostname 'lede'
        option timezone 'UTC'
        option ttylogin '0'
        option log_size '64'
        option urandom_seed '0'

config timeserver 'ntp'
        option enabled '1'
        option enable_server '0'
        list server '0.lede.pool.ntp.org'
        list server '1.lede.pool.ntp.org'
        list server '2.lede.pool.ntp.org'
        list server '3.lede.pool.ntp.org'
```

**Comment by riptidewave93** [comment]
Hey @Gr4ffy thanks for the output. As for the issue with the LEDs, seems that your BIOS may have a different BIOS table thus the difference in "board names" causing the detection to fail. Can you please confirm the BIOS version of your board? You can also try updating the following files:

https://github.com/riptidewave93/Openwrt-APU2/blob/lede-watchdog/overlay/target/linux/x86/base-files/etc/diag.sh#L11
https://github.com/riptidewave93/Openwrt-APU2/blob/lede-watchdog/overlay/target/linux/x86/base-files/etc/board.d/01_leds#L14
https://github.com/riptidewave93/Openwrt-APU2/blob/lede-watchdog/overlay/target/linux/x86/base-files/etc/board.d/02_network#L15

to use "pc-engines-apu2" instead of "APU2" and that should fix the issue.

EDIT: I also plan on getting another APU2 so I can help develop this more "on hands" within the next month or two.

**Comment by Gr4ffy** [comment]
Yep, this is it.
I made changes in those files - "apu2" -> "pc-engines-apu2" and now board detection works fine.

```
My BIOS is:
Vendor: coreboot
    Version: 88a4f96
    Release Date: 03/07/2016

System Information
    Manufacturer: PC Engines
    Product Name: apu2
    Version: 1.0
```

In OpenWrt CC form your repo, everything worked fine.
I didn't changed BIOS, in CC x86.sh was different (dmidecode).

I'll make some tests with build script after work and then LEDE-APU2 should be finished.

Thx @riptidewave93

**Comment by Gr4ffy** [comment]
https://github.com/Gr4ffy/Openwrt-APU2/tree/lede-watchdog
- AES-NI support
- NCT5104 GPIO driver
- watchdog driver
- SD/MMC driver
- PC Speaker (+busybox beep)
- CPU scaling ( default - ondemand )
- default editor -> nano
- sysinfo -> https://github.com/obsy/packages/tree/master/sysinfo

**Comment by riptidewave93** [comment]
@Gr4ffy thanks for sharing. using your initial shares, I will re-base my branches later once my 2nd APU2C4 board arrives, and work on creating a bare-metal base image. (without LuCI packages and whatnot, so other people can use this as a base)

**Comment by riptidewave93** [comment]
Rebase is currently on branch lede-rebase, which will become master in a week or so once my new unit comes in for testing.
