### ISSUE TITLE
Reboot issue with Sierra Wireless MC7455

### ISSUE THREAD

**Issue by jakieu** [riptidewave93/LEDE-APU2#11]
There is an outstanding issue with rebooting the APU2 if a Sierra Wireless MC7455 LTE Modem is installed. This affects not only LEDE but every operating system (I tried Arch and LEDE). After a reboot via Webinterface or console, the MC7455 doesn't get recognized anymore. No device is shown with lsusb nor dmesg. After unplugging the power cord, everything works fine again. To fix the issue, 'reboot=pci' should be added into the grub config file (GRUB_CMDLINE_LINUX_DEFAULT="").

**Comment by riptidewave93** [comment]
@jakieu while this isn't specific to this LEDE image, do you know the PCI ID for this card? I also recommend sharing this on the official PCEngines forum at pcengines.info as this is an unofficial port, and this bug isn't directly related to this image.

**Comment by jakieu** [comment]
I already mentioned it at [pcengines.info](http://www.pcengines.info/forums/?page=post&id=7363B0B2-235E-4CDD-83DE-5669D9CCAAD2&fid=DF5ACB70-99C4-4C61-AFA6-4C0E0DB05B2A) but haven't got any feedback so far. I know that this isn't an issue with your port but I think it's the easiest that you add the workaround. ;-) I'll look at the IDs when I'm back home.

**Comment by riptidewave93** [comment]
Fair enough. As for the card, I am not going to add this change for now mainly because:
1. This card is not sold via PCEngines, so it's not an "official" part.
2. It's impossible to add quirks for "every use case" on the planet for other hardware, so small tweaks like CMDLINE should be left to the user, or builder.

**Comment by jakieu** [comment]
I can understand that. Would you explain to me in short how I can add this to the source before building it?

**Comment by riptidewave93** [comment]
@jakieu Sure thing! You just need to add it to the image Makefile so it's added via grub. https://github.com/lede-project/source/blob/master/target/linux/x86/image/Makefile#L59 Note that this line is for ext4 builds, with the squashfs one below this.

EDIT: It also looks like CONFIG_GRUB_BOOTOPTS is called, so you can define your addition in your build config. Ex, CONFIG_GRUB_BOOTOPTS="option=value"

**Comment by jakieu** [comment]
USB ID of MC7455 is 1199:9071

But adding reboot=pci to the Makefile works like a charm, thank you :)
