### ISSUE TITLE
J17 Header

### ISSUE THREAD

**Issue by Yurannich** [riptidewave93/LEDE-APU2#12]
Hi, Chris! I want to know if NCT5104D driver is implemented (and I want to add some LEDs to front panel) how can I drive with J17 header for this?

**Comment by CRCinAU** [comment]
Yes, however its a bit tricky. You can use the watchdog functions - OR the GPIO functions.

@riptidewave93 can correct me if I'm wrong, but I think by default he builds the watchdog functions?

**Comment by riptidewave93** [comment]
@CRCinAU Correct, by default the build uses the watchdog driver, but more info on using I2C is documented in the PR at https://github.com/riptidewave93/LEDE-APU2/pull/5#issuecomment-255667736
