### ISSUE TITLE
Switch (Vlans) doesn't appear/work ?

### ISSUE THREAD

**Issue by KyleSanderson** [riptidewave93/LEDE-APU2#13]
I manually added:

config switch 'eth2'
        option enable '1'
        option enable_vlan '1'

after

config interface 'Guest'
        option proto 'static'
        option ifname 'eth2.80'
        option ipaddr '10.24.80.1'
        option netmask '255.255.255.0'

However I get `Switch "eth2" has an unknown topology - the VLAN settings might not be accurate.`. This looks like a bug because igb definitely supports vlans.

**Comment by KyleSanderson** [comment]
@riptidewave93 confirmed.

https://github.com/openwrt/luci/commit/8cd6e4efe8351735f93f4c40882ac0cc9c773751

**Comment by riptidewave93** [comment]
@KyleSanderson you can use VLANs without setting the port to a switch. As no switch hardware exists, this could cause your issue. Try removing your config switch part of your config, and reboot. Just defining eth2.80 as its own interface should work.

**Comment by KyleSanderson** [comment]
Absolutely bizarre, those are usually almost always interface aliases. 8021q is also missing...

Thanks Chris.
