### ISSUE TITLE
Support for NCT5104D Super IO chip

### ISSUE THREAD

**Issue by riodda** [riptidewave93/LEDE-APU2#14]
i would like to really thank you for your effort in setting this repo up for the APU2 board.
I successfully build to the APU3A2 board with boot from SD.
I would consider a couple of improvements such as the support for NCT5104D and the default compile options  -march=btver2 -mtune=btver2 to optimize code for the Jabuar SOC, unfortunately i'm not experinced enough to do it myslef.
Here is the kernel patch for the super IO chip

https://pcengines.ch/file/nct5104.tar.bz2

Thanks !

**Comment by riptidewave93** [comment]
@riodda support for that chip is already added in my up-bring branch at https://github.com/riptidewave93/LEDE-APU2/tree/lede-upstream-port, specifically at https://github.com/riptidewave93/LEDE-APU2/blob/lede-upstream-port/overlay/target/linux/x86/files/drivers/gpio/gpio-nct5104d.c

Same with CPU optimization. https://github.com/riptidewave93/LEDE-APU2/blob/lede-upstream-port/config/diffconfig#L34
