### ISSUE TITLE
Reboot from SD Card

### ISSUE THREAD

**Issue by riodda** [riptidewave93/LEDE-APU2#15]
[Uploading putty.zip…]()
I have a strange behaviour from the board booting from SD card.
After Power Reset all is good, the board boots properly, if invoke a reboot command from console (SSH) the board reboots but the sd card even if is detected is in timeout and the board starts with the memory check, plase see console loge.
I don't know frankly if is a bug or if is a mistake from my side in the config.

**Comment by rotanid** [comment]
as you can see in pcengines forum and issue #2 , this is a known problem with some sd cards together with the APU2 chip.
i solved it by using a different sdcard model.

**Comment by riodda** [comment]
Thanks, for the records ADATA MLC SDHC I 1 industrial temperature 8GB boots but don't reboot.
I'm move to a SSD anyway.

**Comment by rotanid** [comment]
for me also a "industrial" one from transcend didn't work, maybe same hardware with different name

**Comment by riptidewave93** [comment]
Going to close this out as this is an upstream issue with Coreboot & the PC Engines APU2, and not related to the LEDE-APU2 port.
