### ISSUE TITLE
Fix PR to add APU drivers to x64

### ISSUE THREAD

**Issue by Strykar** [riptidewave93/LEDE-APU2#17]
@riptidewave93 Could you shed some light on what nbd means when he refused the PR?  https://github.com/lede-project/source/pull/883

**Comment by riptidewave93** [comment]
@Strykar TL;DR they don't want a profile for the APU2 under x64, they would rather see core drivers added to the generic profile for the target. I plan on doing a PR for this, but there are some bugs/issues I am hitting, and I need to work those out before I can do a PR.

Mainly, there seems there is an issue/bug somewhere with LED & Button integration.

**Comment by Strykar** [comment]
@riptidewave93 Thanks for clearing that up, we'll be here when you need some more testing. Thanks.

**Comment by shmedia** [comment]
do you know if the current status made it into 17.01.1?
and i guess you still plan on fixing the remaining issues (and maybe opt for backport to 17.0.1)?

**Comment by rotanid** [comment]
do you know if the current status made it into 17.01.1?
and i guess you still plan on fixing the remaining issues (and maybe opt for backport to 17.0.1)?

**Comment by riptidewave93** [comment]
@rotanid Per https://github.com/lede-project/source/tree/v17.01.1/package/kernel/leds-apu2, the driver exists in 17.01.1, but as the packages are not in the x64 profile they need to be installed with opkg.

Technically all the hard work is done. Just install 17.01.1, and opkg the packages you want. If you are unsure what is needed for board support, you can look at https://github.com/riptidewave93/LEDE-APU2/blob/master/overlay/target/linux/x86/64/profiles/001-PCEngines.mk to get an idea.

As for getting these APU drivers into x86/64, I have been busy with other projects and LEDE devices. It's still on my plate, but lower on my list as the actual hard part (getting the drivers merged) is complete.

**Comment by riptidewave93** [comment]
No longer have plans on continuing this as core functionality is added by the x86_64 target, and other packages can be installed after the fact. closing out this issue
