### ISSUE TITLE
APU3 Bios 4.0.7.1 Broken LEDS

### ISSUE THREAD

**Issue by riodda** [riptidewave93/LEDE-APU2#18]
Hi, i've tryed to upgrade the APU3 bios and after that the apu2 leds support is broken (the leds don't show up in the lede leds configuration, i can only see mmc0 led).
Also the simswitch seems to be floating and uninitialized, it's behaviour changes enabling or diabling the extra 2 uarts, that anyway don't show up in the devs.
I'm more than happy to test any workaroud.

**Comment by CRCinAU** [comment]
Not sure if any of us have an APU3.... Patches welcome I guess?

**Comment by riodda** [comment]
I would I would love to be able to suggest a patch, i can only point to the github for the APU3

https://github.com/pcengines/apu_gpio_lib

Looks that the only difference is the simswap

**Comment by riptidewave93** [comment]
@riodda This is most likely due to the device name change in the latest BIOS. To confirm this, can you share the output of the following?
```
cat /sys/devices/virtual/dmi/id/sys_vendor
cat /sys/devices/virtual/dmi/id/board_vendor
cat /sys/devices/virtual/dmi/id/product_name
cat /sys/devices/virtual/dmi/id/board_name
```

**Comment by riodda** [comment]
Original Bios 20160519

cat /sys/devices/virtual/dmi/id/sys_vendor
PC Engines
cat /sys/devices/virtual/dmi/id/board_vendor
PC Engines
cat /sys/devices/virtual/dmi/id/product_name
apu2
cat /sys/devices/virtual/dmi/id/board_name
apu2

This with bios 4.0.7.1 

cat /sys/devices/virtual/dmi/id/sys_vendor
PC Engines
cat /sys/devices/virtual/dmi/id/board_vendor
PC Engines
cat /sys/devices/virtual/dmi/id/product_name
APU3
cat /sys/devices/virtual/dmi/id/board_name
APU3

and this with bios 4.5.5

cat /sys/devices/virtual/dmi/id/sys_vendor
PC Engines
cat /sys/devices/virtual/dmi/id/board_vendor
PC Engines
cat /sys/devices/virtual/dmi/id/product_name
PCEngines apu3
cat /sys/devices/virtual/dmi/id/board_name
PCEngines apu3

**Comment by riodda** [comment]
had a look to the code and i've found line 311 in leds-apu2.c 

`if (!board_name || !board_vendor || strcasecmp(board_vendor, "PC Engines") || strcasecmp(board_name, "apu2")) 
`

But for my little C understanding we have an OR there and the board vendor is the same for all the bioses.

Also in the feed i donwloaded to build i found a slight different code 

` if (!dmi_match(DMI_BOARD_VENDOR, "PC Engines") || !dmi_match(DMI_BOARD_NAME, "APU2"))`

And i guess case senstitivity should matter....

**Comment by riptidewave93** [comment]
@riodda Once https://github.com/lede-project/source/pull/1206 is merged that should fix it for BIOS 4.0.7.1 but it may not resolve for 4.5.5 If you can, could you test and confirm? It may be worth leaving a note on that PR about the new "board_name" reported on BIOS 4.5.5 to ensure compatibility.

**Comment by riodda** [comment]
I will try to build and test, recently i'm haveing a lot of building errors i hope to get them sorted.
I don't know how to make a note about bios 4.5.5

**Comment by riodda** [comment]
I also have a question, the new firmare enables uart C and uart D, will them show up once the board name is fixed ? i think those are part of the multi io IC that triggers the leds.

**Comment by pietrushnic** [comment]
@riodda we would be glad to help you solve any problems. Can you elaborate little bit more about building issues ?

BTW we recently released new version of BIOS. Please note that if you include sorbootorder payload you can change various things ie. enable disable UART C/D.

**Comment by riodda** [comment]
I normally have building issues with some packages, it was can utils in the past, now if i select some packages that dempends on perl i have a build error, also with the ssl i have build errors but it's mainly my fault i tend to select more packages that what i actually need.
I was trying to manually put the new code but in don't see the lede-apu2.c file locally even if i did feeds install -a

About the uart C/D i've seen it, it was a feature i really needed (this is why i upgraded the firmware) but they don't show in the /dev folder i guess due to the broken gpio package, or i miss some other kernel driver ?

**Comment by riodda** [comment]
I could not wait the merge and i edited manually but seems to be loading from the kernel messages, i haven't tested that much, still no sign of the extra uarts (even if i enabled them in the bios).

`[    4.597602] leds-apu2: load APU2/LED GPIO driver module
[    4.603059] leds-apu2: PCI Revision ID: 0x42
[    4.607595] leds-apu2: APU2 GPIO/LED driver module loaded
`
[https://www.dropbox.com/s/8stybvthai80gf1/bootlog.txt?dl=0](url)

**Comment by pietrushnic** [comment]
@riodda I tested that on Voyage Linux, which is our default system while flashing. Can you point me how I can quickly install LEDE on USB ?

I will test UART C/D on v4.0.7 (I don't have APU3 in home) and most recent v4.0.10 and v4.5.8, then will let you know if things work on Voyage Linux.

**Comment by riodda** [comment]
i will send tomorrow a dropbox link with a basic build with the modifyed led-apu2.c , what is the kernel module that should load uart c and d on voyage ?

**Comment by pietrushnic** [comment]
@riodda please take look at this log for APU2 using v4.0.7:

```
Debian GNU/Linux 8 voyage ttyS0

voyage login: root
Password: 
Last login: Mon Jul 10 19:05:19 GMT 2017 on ttyS0
Linux voyage 3.16.7-ckt9-voyage #1 SMP Wed Apr 22 23:04:57 HKT 2015 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
 __  __
 \ \/ /___ __  __ ___  ___  ___    Useful Commands:
  \  // _ \\ \/ /,-_ |/ _ |/ -_)     remountrw - mount disk as read-write
   \/ \___/ \  / \___,\_  |\___|     remountro - mount disk as read-only
           _/_/        _'_|          remove.docs - remove all docs and manpages 
     { V o y a g e } - L i n u x     
      < http://linux.voyage.hk >   Version: 0.10.0 (Build Date 20150429)  
 
root@voyage:~# dmesg|grep tty
[    4.307515] 00:02: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    4.336083] serial8250: ttyS1 at I/O 0x2f8 (irq = 3, base_baud = 115200) is a 16550A
[    4.364797] serial8250: ttyS2 at I/O 0x3e8 (irq = 4, base_baud = 115200) is a 16550A
[    4.393646] serial8250: ttyS3 at I/O 0x2e8 (irq = 3, base_baud = 115200) is a 16550A
```

Voyage is Debian based, so I assume things should work on your side. I'm building LEDE from master. Is this correct branch to test ? I'm not sure what would be result of this build.

**Comment by riodda** [comment]
I build the image from the script of this repo and i think is using the nigtlies.

**Comment by pietrushnic** [comment]
@riodda if there is any way I can help you in debugging please let me know. I have APU2 and during office hours I can test on APU3.

**Comment by riodda** [comment]
Many thanks Piotr , please just try a lede build on an apu3 with 4.0.7.1 and see if ttyS2 and ttyS3 will show up, as you can see from my bootlog on my board don't show up, i boot on msata bios 4.0.7.1 uard c and d enableb on the bios.

**Comment by pietrushnic** [comment]
@riodda any chance you can try [Voyage](https://github.com/pcengines/apu2-documentation#building-firmware-using-apu2-image-builder) it would add some data point. I will try to organize tests of APU3 as soon as possible and will back with results.

**Comment by riodda** [comment]
Hi Piotr, i've tryed with tynylinux and the extra tty are showing up but not with openwrt/lede, that's quite strange therfore is not an hardware/bios issue, what is the kernel module that the 2 extra serials are relying on ?

**Comment by CRCinAU** [comment]
Also curious if you've tried my nightly builds here: http://openwrt.crc.id.au/

I haven't tested these at all on an APU3, but these images are built nightly from the LEDE trunk.

**Comment by riodda** [comment]
They should be ok after https://github.com/lede-project/source/pull/1206 will be merged. I'm rebuilding with the 8250 module in the kernel it was not build i hope is the problem.

**Comment by riodda** [comment]
i confirm that with the kernel module the extra uart are showing now
[    1.478960] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    1.506252] 00:02: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    1.534480] serial8250: ttyS1 at I/O 0x2f8 (irq = 3, base_baud = 115200) is a 16550A
[    1.563025] serial8250: ttyS2 at I/O 0x3e8 (irq = 4, base_baud = 115200) is a 16550A
[    1.591569] serial8250: ttyS3 at I/O 0x2e8 (irq = 3, base_baud = 115200) is a 16550A

**Comment by pietrushnic** [comment]
@riodda great you manage to make it work. If you will have any problems with coreboot or PC Engines platforms firmware do not hesitate to ping me.

**Comment by riptidewave93** [comment]
@riodda and @pietrushnic,

Going to close this issue out as the resolution is pending at https://github.com/lede-project/source/pull/1206. Feel free to re-open if there are any objections.
