### ISSUE TITLE
Missing support of SIMSWITCH

### ISSUE THREAD

**Issue by riodda** [riptidewave93/LEDE-APU2#19]
Lookslike that now the leds-apu2 works ok on the led side, but this simswitch is not supported and this leaves the simcontrol gpio floating and preventing the system to correctly access the simcard.

`root@lede:~# cat /sys/kernel/debug/gpio
GPIOs 0-7, platform/gpio-nct5104d, gpio-nct5104d, can sleep:

GPIOs 10-17, platform/gpio-nct5104d, gpio-nct5104d, can sleep:

GPIOs 495-506, pci/0000:04:00.0, ath9k-phy0:
 gpio-496 (                    |ath9k-phy0          ) out hi

GPIOs 507-511, platform/leds-apu2, leds-apu2:
 gpio-507 (                    |Reset button        ) in  hi
 gpio-509 (                    |apu2:green:power    ) out hi
 gpio-510 (                    |apu2:green:led2     ) out hi
 gpio-511 (                    |apu2:green:led3     ) out hi
`

**Comment by riptidewave93** [comment]
Hey @riodda, have you tried manually exporting the GPIO via sysfs for manual access? This repo was originally intended for the APU2, so this request is probably more relevant for the PR at https://github.com/lede-project/source/pull/1206

**Comment by pietrushnic** [comment]
@mek-x do we need any adjustment for APU3 ?

**Comment by mek-x** [comment]
@pietrushnic I believe APU3 has the same routing for it's leds. It should work

**Comment by riodda** [comment]
I confirm leds are working ok on APU3, just sim switch not exposed but looks like it's inizialized correctly and not floating as i was supposed (it's just the opposite to old firmware and my previous lede build).

**Comment by riptidewave93** [comment]
Closing this out as it's not related to this repo directly, as the driver in question is upstream in LEDE and this issue should be handled there.
