### ISSUE TITLE
Use the latest release instead of the master?

### ISSUE THREAD

**Issue by joe9** [riptidewave93/LEDE-APU2#20]
Hello,

Thanks for sharing your effort. It made it so much easier to build the image.

Now that all your patches are in the release (17.01.3), just want to check if it is a good idea to use that release in build.sh (instead of cloning the latest head).

As an fyi, I could not build with gcc-5.4 (the default) as I kept running into compile issues. gcc 6.3 worked fine.

Thanks again

**Comment by Strykar** [comment]
I edited `build.sh` to `git clone -b v17.01.4` and it compiles fine.

**Comment by riptidewave93** [comment]
Hello,

As most of the core components for the APU2 were merged into mainline LEDE, I really don't have any intentions of updating/maintaining this repo anymore.
