### ISSUE TITLE
CONFIG_PACKAGE_ath10k-firmware-qca988x=y required for wle600vx

### ISSUE THREAD

**Issue by joe9** [riptidewave93/LEDE-APU2#21]
Hello

CONFIG_PACKAGE_ath10k-firmware-qca988x=y is required to bring up the wle600vx card interfaces.

Just want to check if you might be interested in adding it to the build profile.

Thanks

**Comment by riptidewave93** [comment]
Hello,

Thanks for reaching out. Sadly I no longer have intent of maintaining this repo as the core drivers needed for APU2 support were merged upstream in LEDE. If you this repo for your builds, I recommend forking it and maintaining your own fork with the changes your board requires.
