### ISSUE TITLE
Add CPU optimisation

### ISSUE THREAD

**Issue by CRCinAU** [riptidewave93/LEDE-APU2#3]
Via:
https://volatilesystems.org/optimising-lede-openwrt-for-the-pc-engines-apu2.html

GCC has its own target for the Jaguar SoCs. You can optimise by using the -march=btver2 -mtune=btver2 GCC options, with a recent GCC version. In the buildroot, enable Advanced configuration options (for developers), then tick Target Options and add the compiler flags to Target Optimizations.

**Comment by riptidewave93** [comment]
Resolved and discussed at https://github.com/riptidewave93/LEDE-APU2/pull/6
