### ISSUE TITLE
Ship SP5100 driver as a kmod

### ISSUE THREAD

**Issue by CRCinAU** [riptidewave93/LEDE-APU2#9]
Not exactly sure what to do about this - but as I understand it, the following applies:

1) If you use the SP5100 as a watchdog, you cannot load it as an i2c device.
2) If you use the i2c device, you can't use the watchdog.

My proposal is to build the SP5100 driver as a kmod and allow the user to select / install which specific one you want to use. In my builds, I've got the 'kmod-i2c-piix4' package built automatically - but the SP5100 has no rules / package to create a kmod.

The .config I use has:
CONFIG_ALL_KMODS=y

I only made the following change:

```
diff --git a/overlay/target/linux/x86/64/config-default b/overlay/target/linux/x86/64/config-default
index 13ff5dd..0c0c3d8 100644
--- a/overlay/target/linux/x86/64/config-default
+++ b/overlay/target/linux/x86/64/config-default
@@ -206,7 +206,7 @@ CONFIG_SATA_AHCI=y
 CONFIG_SCSI_VIRTIO=y
 CONFIG_SERIAL_8250_PNP=y
 CONFIG_SMP=y
-CONFIG_SP5100_TCO=y
+CONFIG_SP5100_TCO=m
 CONFIG_SPARSEMEM=y
 CONFIG_SPARSEMEM_ALLOC_MEM_MAP_TOGETHER=y
 CONFIG_SPARSEMEM_EXTREME=y
```

**Comment by CRCinAU** [comment]
As a side note, I also set:

```
CONFIG_BUSYBOX_CUSTOM=y
CONFIG_BUSYBOX_CONFIG_I2CGET=y
CONFIG_BUSYBOX_CONFIG_I2CSET=y
CONFIG_BUSYBOX_CONFIG_I2CDUMP=y
CONFIG_BUSYBOX_CONFIG_I2CDETECT=y
```

This gives the userland tools to play with i2c.

**Comment by riptidewave93** [comment]
@CRCinAU Originally sp5100_tco was shipped as a kmod for the device, but per feedback from Felix at http://lists.infradead.org/pipermail/lede-dev/2016-October/003561.html he preferred it built into the kernel. If you want the kmod back, I recommend replying with your reasons.

**Comment by CRCinAU** [comment]
Now - I'm kinda wondering... have I made a mistake and the SP5100 also controls the LEDs D4 D5?

I have D6 on (power), but now I no longer see the other LEDs in /sys/class/leds.

**Comment by riptidewave93** [comment]
the SP5100 driver should not have an affect on the LEDs. You can verify the LED driver loaded by checking dmesg for messages from "leds-apu2"

`dmesg | grep leds-apu2`

**Comment by CRCinAU** [comment]
Ok, nothing in there - I've messed something else up then :)

```
root@lede:/# dmesg | grep -i leds
root@lede:/#
```

Let me review....

**Comment by riptidewave93** [comment]
Closing this for now as feedback for this should be left at http://lists.infradead.org/pipermail/lede-dev/2016-October/003561.html
